### ISSUE TITLE
strict gctorture results to work through

### ISSUE THREAD

**Issue by mattdowle** [Rdatatable/data.table#4628]
With R-devel compiled with clang-10, strict barrier and gctorture too (see CRAN_Release.cmd for commands). Hasn't finished yet, but this is output so far is below.
The 1036.* fails probably are knock-on effects from the first 1036.02.
Unlikely to be a memory fault related to gctorture. More likely some extra strict checks turned on when strict barrier is on too, possibly new in latest R-devel.
```
> print(Sys.time()); started.at<-proc.time(); try(test.data.table()); print(Sys.time()); print(timetaken(started.at))
[1] "2020-07-21 00:39:28.074113 MDT"
getDTthreads(verbose=TRUE):
This installation of data.table has not been compiled with OpenMP support.
  omp_get_num_procs()            1
  R_DATATABLE_NUM_PROCS_PERCENT  unset (default 50)
  R_DATATABLE_NUM_THREADS        unset
  R_DATATABLE_THROTTLE           unset (default 1024)
  omp_get_thread_limit()         1
  omp_get_max_threads()          1
  OMP_THREAD_LIMIT               unset
  OMP_NUM_THREADS                unset
  RestoreAfterFork               true
  data.table is using 1 threads with throttle==1024. See ?setDTthreads.
test.data.table() running: /home/mdowle/build/R-devel-strict-clang/library/data.table/tests/tests.Rraw 
Running test id 1036.02      Test 1036.02 didn't produce the correct warning :
Expected: All measure variables not of type 'character' will be coerced 
Observed: type 31 is unimplemented in 'type2char' 
Test 1036.02 produced 1 errors but expected 0
Expected: 
Observed: CAR/CDR/TAG or similar applied to unknown type #31 object
Running test id 1036.03      Test 1036.03 ran without errors but failed check that x equals y:
> x = length(levels(ans$variable)) 
First 1 of 1 (type 'integer'): 
[1] 100
> y = 317L 
First 1 of 1 (type 'integer'): 
[1] 317
Mean relative difference: 2.17
Running test id 1036.04      Test 1036.04 ran without errors but failed check that x equals y:
> x = levels(ans$variable)[c(1, 2, 316, 317)] 
First 4 of 4 (type 'character'): 
[1] "V1" "V2" NA   NA  
> y = tt <- c("Geography", "Estimate; SEX AND AGE - Total population",      "Percent; HISPANIC OR LATINO AND RACE - Total housing units",      "Percent Margin of Error; HISPANIC OR LATINO AND RACE - Total housing units") 
First 4 of 4 (type 'character'): 
[1] "Geography"                                                                 
[2] "Estimate; SEX AND AGE - Total population"                                  
[3] "Percent; HISPANIC OR LATINO AND RACE - Total housing units"                
[4] "Percent Margin of Error; HISPANIC OR LATINO AND RACE - Total housing units"
'is.NA' value mismatch: 0 in current 2 in target
Running test id 1036.05      Test 1036.05 ran without errors but failed check that x equals y:
> x = range(as.integer(ans$variable)) 
First 2 of 2 (type 'integer'): 
[1]   1 100
> y = INT(1, 317) 
First 2 of 2 (type 'integer'): 
[1]   1 317
Mean relative difference: 2.17
Running test id 1036.06      Test 1036.06 ran without errors but failed check that x equals y:
> x = as.vector(table(table(as.integer(ans$variable)))) 
First 1 of 1 (type 'integer'): 
[1] 100
> y = INT(309, 8) 
First 2 of 2 (type 'integer'): 
[1] 309   8
Numeric: lengths (1, 2) differ
Running test id 1036.07      Test 1036.07 ran without errors but failed check that x equals y:
> x = sapply(ans, class) 
First 2 of 2 (type 'character'): 
 variable     value 
 "factor" "integer" 
> y = c(Id = "character", Id2 = "integer", variable = "factor", value = "character") 
First 4 of 4 (type 'character'): 
         Id         Id2    variable       value 
"character"   "integer"    "factor" "character" 
Names: 2 string mismatches
Lengths (2, 4) differ (string compare on first 2)
1 string mismatch
Running test id 1372.26  

... still running

```

**Comment by mattdowle** [comment]
Type 31 is FREESXP, so it does seem to be a protection problem revealed by gctorture. Will increase torture on test 1036 next after #4629 is merged.

**Comment by mattdowle** [comment]
For completess, if anyone runs this extra strict test in future, when you `q()` you get the following output from `libfontconfig` which I ignore. In the past there have been `data.table` problems/leaks detected at this stage but if there are, the output points to `datatable.so`, and a line number too so long as `~/.R/Makevars` contained `CFLAGS=-O0 -g` at the time of installing data.table into `Rdevel-strict-clang`.

```
> q()

=================================================================
==2903957==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 6912 byte(s) in 27 object(s) allocated from:
    #0 0x4a89bd in malloc (/home/mdowle/build/R-devel-strict-clang/bin/exec/R+0x4a89bd)
    #1 0x7f77eef512f4  (/usr/lib/x86_64-linux-gnu/libfontconfig.so.1+0x212f4)

Direct leak of 5120 byte(s) in 8 object(s) allocated from:
    #0 0x4a8cd9 in realloc (/home/mdowle/build/R-devel-strict-clang/bin/exec/R+0x4a8cd9)
    #1 0x7f77eef513a0  (/usr/lib/x86_64-linux-gnu/libfontconfig.so.1+0x213a0)

Indirect leak of 17408 byte(s) in 544 object(s) allocated from:
    #0 0x4a89bd in malloc (/home/mdowle/build/R-devel-strict-clang/bin/exec/R+0x4a89bd)
    #1 0x7f77eef3d54f  (/usr/lib/x86_64-linux-gnu/libfontconfig.so.1+0xd54f)

Indirect leak of 8552 byte(s) in 690 object(s) allocated from:
    #0 0x494d64 in strdup (/home/mdowle/build/R-devel-strict-clang/bin/exec/R+0x494d64)
    #1 0x7f77eef50b64 in FcValueSave (/usr/lib/x86_64-linux-gnu/libfontconfig.so.1+0x20b64)

Indirect leak of 6304 byte(s) in 197 object(s) allocated from:
    #0 0x4a8b32 in calloc (/home/mdowle/build/R-devel-strict-clang/bin/exec/R+0x4a8b32)
    #1 0x7f77eef5193c  (/usr/lib/x86_64-linux-gnu/libfontconfig.so.1+0x2193c)

Indirect leak of 3072 byte(s) in 96 object(s) allocated from:
    #0 0x4a8b32 in calloc (/home/mdowle/build/R-devel-strict-clang/bin/exec/R+0x4a8b32)
    #1 0x7f77eef50e0f  (/usr/lib/x86_64-linux-gnu/libfontconfig.so.1+0x20e0f)

Indirect leak of 768 byte(s) in 24 object(s) allocated from:
    #0 0x4a8b32 in calloc (/home/mdowle/build/R-devel-strict-clang/bin/exec/R+0x4a8b32)
    #1 0x7f77eef50cae  (/usr/lib/x86_64-linux-gnu/libfontconfig.so.1+0x20cae)

Indirect leak of 256 byte(s) in 8 object(s) allocated from:
    #0 0x4a8b32 in calloc (/home/mdowle/build/R-devel-strict-clang/bin/exec/R+0x4a8b32)
    #1 0x7f77eef50d16  (/usr/lib/x86_64-linux-gnu/libfontconfig.so.1+0x20d16)

Indirect leak of 192 byte(s) in 4 object(s) allocated from:
    #0 0x4a89bd in malloc (/home/mdowle/build/R-devel-strict-clang/bin/exec/R+0x4a89bd)
    #1 0x7f77eef4ae11 in FcLangSetCreate (/usr/lib/x86_64-linux-gnu/libfontconfig.so.1+0x1ae11)

SUMMARY: AddressSanitizer: 48584 byte(s) leaked in 1598 allocation(s).
```
