### ISSUE TITLE
fread crashes R (bus error) for large gzipped csv file when specifying a large number of nrows (but whole file works)

### ISSUE THREAD

**Issue by dbgoodman** [Rdatatable/data.table#5882]
I have large gzipped csv file with ~40 million rows. I can read the whole file into R fine:

```
filename <- 'myfile.csv'
table_whole <- fread(filename)
```

I can also load about 5e6 rows into R fine:
```
filename <- 'myfile.csv'
table_first5e6rows <- fread(filename, nrows=5e6)
```

But, when I load 10e6 rows, it crashes R:

```
filename <- 'myfile.csv'
table_first5e6rows <- fread(filename, nrows=1e7)
 *** caught bus error ***
address 0x20000180e, cause 'invalid alignment'
```

Here is the actual output with the actual file, with verbose on:
```
> library(data.table)
data.table 1.14.10 using 8 threads (see ?getDTthreads).  Latest news: r-datatable.com
> fread('/Users/dbg/Library/CloudStorage/Box-Box/tcsl/ngs_data/2023.09.12.illumina_28/out/merged_df.csv.gz', nrows=1e7, verbose=T)
  OpenMP version (_OPENMP)       202011
  omp_get_num_procs()            16
  R_DATATABLE_NUM_PROCS_PERCENT  unset (default 50)
  R_DATATABLE_NUM_THREADS        unset
  R_DATATABLE_THROTTLE           unset (default 1024)
  omp_get_thread_limit()         2147483647
  omp_get_max_threads()          16
  OMP_THREAD_LIMIT               unset
  OMP_NUM_THREADS                unset
  RestoreAfterFork               true
  data.table is using 8 threads with throttle==1024. See ?setDTthreads.
Input contains no \n. Taking this to be a filename to open
[01] Check arguments
  Using 8 threads (omp_get_max_threads()=16, nth=8)
  NAstrings = [<<NA>>]
  None of the NAstrings look like numbers.
  show progress = 1
  0/1 column will be read as integer
[02] Opening the file
  Opening file /var/folders/r9/rhdgkfwx0msg9ldkp_6ltypr0000gn/T//RtmpkxLujJ/file1018d1112866
  File opened, size = 10.67GB (11454682052 bytes).
  Memory mapped ok
[03] Detect and skip BOM
[04] Arrange mmap to be \0 terminated
  \n has been found in the input and different lines can end with different line endings (e.g. mixed \n and \r\n in one file). This is common and ideal.
[05] Skipping initial rows if needed
  Positioned on line 1 starting: <<itam_bc_o,itam_umi_o,costim_bc>>
[06] Detect separator, quoting rule, and ncolumns
  Detecting sep automatically ...
  sep=','  with 100 lines of 94 fields using quote rule 0
  Detected 94 columns on line 1. This line is either column names or first data row. Line starts as: <<itam_bc_o,itam_umi_o,costim_bc>>
  Quote rule picked = 0
  fill=false and the most number of columns found is 94
[07] Detect column types, good nrow estimate and whether first row is column names
  Number of sampling jump points = 100 because nrow limit (10000000) supplied
  Type codes (jump 000)    : CCCC755555555555555555555555555555555555555555555555555555555555555555555555555555555555555555  Quote rule 0
  'header' determined to be true due to column 5 containing a string on row 1 and a lower type (float64) in the rest of the 100 sample rows
  All rows were sampled since file is small so we know nrow=100 exactly
[08] Assign column names
[09] Apply user overrides on column types
  After 0 type and 0 drop user overrides : CCCC755555555555555555555555555555555555555555555555555555555555555555555555555555555555555555
[10] Allocate memory for the datatable
  Allocating 94 column slots (94 - 0 dropped) with 100 rows
[11] Read the data
  jumps=[0..1), chunk_size=1048576, total_size=11454676303
  Too few rows allocated. Allocating additional 11999900 rows (now nrows=10000000) and continue reading from jump 0
  jumps=[0..1), chunk_size=1048576, total_size=11454676303

 *** caught bus error ***
address 0x20000180e, cause 'invalid alignment'

Traceback:
 1: fread("/Users/dbg/Library/CloudStorage/Box-Box/tcsl/ngs_data/2023.09.12.illumina_28/out/merged_df.csv.gz",     nrows = 1e+07, verbose = T)
```

I have other similarly sized gzipped CSVs (including some that are 20% larger) that work fine, so it is something about the combination of this file, and asking nrows to load in a large number of rows. 

[Here is a link to the file on box (700MB).](https://ucsf.box.com/s/2nkgo1u5vas5vycup1krukgaib6t6y0r) 

Here is my session info:
```
> sessionInfo()
R version 4.3.2 (2023-10-31)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Sonoma 14.1

Matrix products: default
BLAS:   /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/lib/libRblas.0.dylib 
LAPACK: /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.11.0

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

time zone: America/Los_Angeles
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.3.2
```

**Comment by tdhock** [comment]
did you try using the dev version of fread?
```r
data.table::update_dev_pkg()
```

**Comment by aitap** [comment]
Reproduces in 6cee825fa1b05a8ccbf674a5ec5659559d674457, looks like a heap corruption:

```
data.table 1.15.99 IN DEVELOPMENT built 2024-08-18 08:11:35 UTC; ivan using 8 threads (see ?getDTthreads).
# most of the output like in the initial issue
[11] Read the data
  jumps=[0..1), chunk_size=1048576, total_size=11454676303
  Too few rows allocated. Allocating additional 11999900 rows (now nrows=10000000) and continue reading from jump 0
  jumps=[0..1), chunk_size=1048576, total_size=11454676303

Thread 1 "R" received signal SIGSEGV, Segmentation fault.
RunGenCollect (size_needed=93825004979904) at ../../../src/main/memory.c:1755
1755                    FORWARD_CHILDREN(s);
(gdb) bt
#0  RunGenCollect (size_needed=93825004979904) at ../../../src/main/memory.c:1755
#1  R_gc_internal (size_needed=size_needed@entry=2) at ../../../src/main/memory.c:3232
#2  0x00005555556e12dc in Rf_allocVector3 (type=<optimized out>, type@entry=73, length=length@entry=15, allocator=allocator@entry=0x0)
    at ../../../src/main/memory.c:2858
#3  0x00005555556e261f in Rf_allocVector (length=15, type=73) at ../../../src/include/Rinlinedfuns.h:597
#4  0x000055555566cbd2 in Rf_mkCharLenCE (
    name=0x7ffcc89a7fc2 "GTCCGTATCCTTTTT,31.0,0,0,0,0,0,1,0,0,0,0,0,18,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,124,0,0,0,0,0,1,0,0,0,0,0,0,22,0,0,0,0,1,0,0,0
,0,0,25,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,2,0,0,"..., len=15, enc=<optimized out>) at ../../../src/main/envir.c:4361
#5  0x000055555566d1c7 in Rf_mkCharLenCE (name=<optimized out>, len=<optimized out>, enc=<optimized out>) at ../../../src/main/envir.c:4463
#6  0x00007fff7324ecc5 in pushBuffer (ctx=ctx@entry=0x7fffffff9fc0) at freadR.c:603
#7  0x00007fff73245e1e in freadMain._omp_fn.0 () at fread.c:2558
#8  0x00007ffff57f70b6 in GOMP_parallel () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
#9  0x00007fff73249273 in freadMain (_args=...) at fread.c:2232
```

AddressSanitizer says...

```
==30431==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x7f7c37bc12fb at pc 0x7f7f65466734 bp 0x7ffcfd90a6a0 sp 0x7ffcfd90a698
READ of size 1 at 0x7f7c37bc12fb thread T0
    #0 0x7f7f65466733 in pushBuffer /tmp/RtmpjwsHnc/R.INSTALL749d1df0bb35/data.table/src/freadR.c:593
    #1 0x7f7f6544e9a0 in freadMain._omp_fn.0 /tmp/RtmpjwsHnc/R.INSTALL749d1df0bb35/data.table/src/fread.c:2558
    #2 0x7f7f6f8bf0b5 in GOMP_parallel (/usr/lib/x86_64-linux-gnu/libgomp.so.1+0x140b5)
    #3 0x7f7f65456576 in freadMain /tmp/RtmpjwsHnc/R.INSTALL749d1df0bb35/data.table/src/fread.c:2232
    #4 0x7f7f65460ff7 in freadR /tmp/RtmpjwsHnc/R.INSTALL749d1df0bb35/data.table/src/freadR.c:218

0x7f7c37bc12fb is located 203 bytes to the right of 40000048-byte region [0x7f7c3559b800,0x7f7c37bc1230)
allocated by thread T0 here:
    #0 0x7f7f702b89cf in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:69
    #1 0x55a5e30e60d7 in Rf_allocVector3 ../../../src/main/memory.c:2889
    #2 0x7f7f653edd30 in growVector /tmp/RtmpjwsHnc/R.INSTALL749d1df0bb35/data.table/src/dogroups.c:521
    #3 0x7f7f6545ed6b in allocateDT /tmp/RtmpjwsHnc/R.INSTALL749d1df0bb35/data.table/src/freadR.c:495
    #4 0x7f7f65456966 in freadMain /tmp/RtmpjwsHnc/R.INSTALL749d1df0bb35/data.table/src/fread.c:2601
    #5 0x7f7f65460ff7 in freadR /tmp/RtmpjwsHnc/R.INSTALL749d1df0bb35/data.table/src/freadR.c:218
```

Where does `str` come from?
https://github.com/Rdatatable/data.table/blob/6cee825fa1b05a8ccbf674a5ec5659559d674457/src/freadR.c#L591-L593
```
(gdb) p *source
$3 = {len = 9, off = -2120483705}
```

What about `source`?
https://github.com/Rdatatable/data.table/blob/6cee825fa1b05a8ccbf674a5ec5659559d674457/src/freadR.c#L584
```
(gdb) p source - buff8_lenoffs
$15 = 45919680
(gdb) p *ctx
$18 = {
  anchor = 0x7ffd41a01674 "GGCTCAGGT,TCTGGGTCAGGGTCC,TCAGGTAGT,TCGCGTTTTCAGCAT,60.0,6079,3,665,0,156,3,4,7,1,2,1,7,1,4307,40,4,3,3,1,0,28,6,2,3,2,154,8,3,1,1,48,17,9,1,3,8,7,3,43,1,8,3,3,2,3,0,5,3,26,252,426,6,2,8,7,2,4,0,36,3,"..., buff8 = 0x7ffc0c780800, buff4 = 0x7ff963e54800,
  buff1 = 0x60200001b850, rowSize8 = 40, rowSize4 = 356, rowSize1 = 0, DTi = 0, nRows = 10000000, stopTeam = 0x7fffffff90a0, threadn = 0,
  quoteRule = 0, nStringCols = 4, nNonStringCols = 90}
```

How did that happen?
```
(rr) reverse-continue
Continuing.

Hardware watchpoint 2: *(lenOff*)(0x7f723eac8e10)

Old value = {len = 9, off = -2120483705}
New value = {len = 9, off = 0}
0x00007f75f5f2e0be in Field (ctx=0x7ffd36e67c20) at fread.c:522
522         target->off = (int32_t)(fieldStart - ctx->anchor);
```
https://github.com/Rdatatable/data.table/blob/6cee825fa1b05a8ccbf674a5ec5659559d674457/src/fread.c#L522
```
(rr) p ctx->anchor
$15 = 0x7f734ae01674 "GGCTCAGGT,TCTGGGTCAGGGTCC,TCAGGTAGT,TCGCGTTTTCAGCAT,60.0,6079,3,665,0,156,3,4,7,1,2,1,7,1,4307,40,4,3,3,1,0,28,6,2,3,2,154,8,3,1,1,48,17,9,1,3,8,7,3,43,1,8,3,3,2,3,0,5,3,26,252,426,6,2,8,7,2,4,0,36,3,"...
(rr) p fieldStart
$26 = 0x7f73cc7c12fb "GGATCAGGA,TCCGGATCTGGTTCG,CTCGCTACA,ACTGCTCCTCTTATT,34.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0"...
(rr) p (fieldStart - ctx->anchor)
$27 = 2174483591
(rr) p (fieldStart - ctx->anchor) > ((1U<<31)-1)
$28 = 1
```

Somehow the code is given a context with a field that is much longer than `INT_MAX`:
https://github.com/Rdatatable/data.table/blob/6cee825fa1b05a8ccbf674a5ec5659559d674457/src/fread.c#L504
```
(rr) p *ctx->ch - ctx->anchor
$42 = 2174483591
```
Where does it come from?

```
(rr) rc
Continuing.

Hardware watchpoint 5: **(const char ***)0x7ffd36e67c20

Old value = 0x7f73d7ed7a65 "GGATCAGGG,TCTGGATCAGGTTCC,AGCCTACTG,CCTCCTCGCTCTATC,34.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0"...
New value = 0x7f73d7ed7a64 "\nGGATCAGGG,TCTGGATCAGGTTCC,AGCCTACTG,CCTCCTCGCTCTATC,34.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"...
```
https://github.com/Rdatatable/data.table/blob/6cee825fa1b05a8ccbf674a5ec5659559d674457/src/fread.c#L2370

As far as I can tell, `tch` is just normally incremented until it's past `fctx.anchor` + 2<sup>31</sup>-1. The code seems to insist on `nJumps = 1` when the number of rows is pre-set, and turns out to be not ready to cover this much data in one jump. I don't understand the overall structure to offer a fix.
